yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(str('group/<slug>/'), views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    objects = None
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


# Create your views here.
class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


# Главная страница
def index(request):
    template = 'posts/index.html'
    text = "Это главная страница проекта Yatube"
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'text': text,
        'posts': posts,
    }
    return render(request, template, context)


# Страница со списком мороженого
def group_posts(request, slug):
    template = 'posts/group_list.html'
    text = "Здесь будет информация о группах проекта Yatube"
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'text': text,
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)


def profile(request, username):
    count = Post.objects.filter(author__username=username).count()
    posts = Post.objects.filter(author__username=username)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': username,
        'count': count
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    count = Post.objects.filter(author=post.author).count()
    context = {
        'post': post,
        'count': count
    }
    return render(request, 'posts/post_detail.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32"
          href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16"
          href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}<title>Последние обновления на сайте</title>{% endblock %}
</head>
<body>
<header>
    {% include 'includes/header.html' %}
</header>

<main>
    {% block content %}
        Контент не подвезли :(
    {% endblock %}
</main>
<footer>
    {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30"
                     class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
            {# Добавлено в спринте #}

            {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
            <ul class="nav nav-pills">
                {% with request.resolver_match.view_name as view_name %}
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
                           href="{% url 'about:author' %}">Об
                            авторе</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
                           href="{% url 'about:tech' %}">Технологии</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link " href="">Новая запись</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light"
                               href="{% url 'password_change' %}">Изменить
                                пароль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light"
                               href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                        <li>
                            Пользователь: {{ user.username }}
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link link-light"
                               href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light"
                               href="{% url 'users:signup' %}">Регистрация</a>
                        </li>
                    {% endif %}
                {% endwith %}
            </ul>
            {# Конец добавленого в спринте #}
        </div>
    </nav>
</header>

yatube/templates/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_cart.html
<ul>
    <li>
        Автор: {{ post.author.get_full_name }}
    </li>
    <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>{{ post.text }}</p>
{% if post.group and not slug %}
    <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
{% endif %}<br>
<a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
{% if not forloop.last %}
    <hr>{% endif %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<h3>все записи группы {{ group }}</h3>
{% for post in posts %}
{% include 'includes/post_cart.html' with slug=post.group.slug %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
{% for post in page_obj %}
{% include 'includes/post_cart.html' %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    <title>Пост {{ post.text|truncatechars:30 }}</title>
{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% if post.group %}
                    <li class="list-group-item">
                        Группа: {{ post.group }}
                        <a href="{% url 'posts:group' post.group.slug %}">
                            все записи группы
                        </a>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>{{ count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author.username %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p>
                {{ post.text }}
            </p>
        </article>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    <title>Профайл пользователя {{ author }}</title>
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ count }} </h3>
        <article>
            {% for post in page_obj %}
                {% include 'includes/post_cart.html' %}
            {% endfor %}
        </article>
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}

                <form method="post"
                      {% if action_url %}
                      action="{% url action_url %}"
                      {% endif %}
                >
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group row my-3"
                         {% if field.field.required %}
                         aria-required="true"
                         {% else %}
                         aria-required="false"
                         {% endif %}
                    >
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        <div>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help"
                                   class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                        <!-- Тест на внимательность. Без переопределения шаблона этого адреса
                        не существует. Нужно что-то делать, иначе все упадет -->
                        <a href=""
                           class="btn btn-link">
                            Забыли пароль?
                        </a>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
-->
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                {% load user_filters %} {# Загружаем фильтры #}
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}

                <form method="post" action="{% url 'users:signup' %}">
                    {% csrf_token %}

                    {# Выводим поля в цикле, по отдельности #}
                    {% for field in form %}
                    <div class="form-group row my-3">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        {# К полю ввода добавляем атрибут class #}
                        {{ field|addclass:'form-control' }}
                        {% if field.help_text %}
                        <small
                                id="{{ field.id_for_label }}-help"
                                class="form-text text-muted"
                        >
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Зарегистрироваться
                        </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}